### ISSUE TITLE
Can't seem to find how to define a new Cohort -> Role sync

### ISSUE THREAD

**Issue by swinster** [paulholden/moodle-local_cohortrole#5]
This is probably me simply not seeing what is right in front of me. We have setup and are using Cohort Role sync, but although `Site admin -> Users -> Accounts -> Cohort Role sync` shows the currently defined sync, I can't seem to see anything to define a new sync. 

It was a while back when I set this up, but I simply can remember how I did this. 

Moodle version is 3.8.2

This is what i see:

![image](https://user-images.githubusercontent.com/8142964/82361687-18361b80-9a03-11ea-8cc6-505dbb4f60b9.png)

**Comment by paulholden** [comment]
Hi @swinster, that's a strange one - there should be an "Add" button right under the table listing existing synchronizations

Do you have a custom theme? Could you inspect the HTML source and confirm whether you have a style that is hiding the button (can't imagine why it would...)

**Comment by swinster** [comment]
Hi Paul,

You can close this out. Your thinking is correct. We asked our partner to see if they remove the "continue" button when a user clicked on courses that they had not registered for. This simply returned them to the course overview page as there is no manual enrolment, as this is done through a separate site. This CSS change had this (and possibly other) unintended side effects.
