### ISSUE TITLE
Invalid user id, when a cohort has deleted users

### ISSUE THREAD

**Issue by haiksu** [paulholden/moodle-local_cohortrole#6]
`local_cohortrole_role_assign` function gives an error, if a cohort has deleted members assigned to it. Usually Moodle unassigns deleted users from cohorts, but that's not reliable.

Before assigning a role, the plugin should check that the user is not deleted.

I'll submit a code improvement in just a few minutes.

**Comment by paulholden** [comment]
Updated in https://github.com/paulholden/moodle-local_cohortrole/pull/16
